#ifndef HEAD_TRANSLATE_CLASS_H_H_HEAD__FILE__
#define HEAD_TRANSLATE_CLASS_H_H_HEAD__FILE__
class DeleteExceptionTranslate;
class AppMusicManageTranslate;
class UserMutexTranslate;
class SystemTrayIconTranslate;
class SystemTrayIconMenuTranslate;
class MainWindowTranslate;
class AboutWidgetTranslate;
class DateTimeFormatTranslate;
class JsonTranslate;
class MessageTranslate;
class MusicWidgetTranslate;
class SettingWidgetTranslate;
class PlayerListWidgetMenuTranslate;
class FavoriteWidgetMenuTranslate;
class AppTranslate;
#endif // HEAD_TRANSLATE_CLASS_H_H_HEAD__FILE__
