#ifndef HEAD_JSON_KEY_CLASS_H_H_HEAD__FILE__
#define HEAD_JSON_KEY_CLASS_H_H_HEAD__FILE__
class AppMusicManageJsonKey;
class AppUserInterfaceManageJsonKey;
class AppDataManageJsonKey;
class SystemTrayIconJsonKey;
class MainWindowJsonKey;
class AboutWidgetJsonKey;
class AppDataJsonKey;
#endif // HEAD_JSON_KEY_CLASS_H_H_HEAD__FILE__
